const CARS=[
{id:1,make:"Toyota",model:"Fortuner 2.4 GD-6",year:2023,price:429900,km:62000,gear:"Automatic",fuel:"Diesel",location:"Johannesburg",type:"SUV",featured:true,dealer:"CARZA Founding Motors",phone:"0110000000",img:"https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=85"},
{id:2,make:"Volkswagen",model:"Tiguan 1.4 TSI",year:2022,price:369900,km:47000,gear:"Automatic",fuel:"Petrol",location:"Pretoria",type:"SUV",featured:true,dealer:"Capital Auto Gallery",phone:"0120000000",img:"https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=85"},
{id:3,make:"BMW",model:"320i M Sport",year:2021,price:399900,km:58000,gear:"Automatic",fuel:"Petrol",location:"Johannesburg",type:"Sedan",featured:false,dealer:"Premium Drive",phone:"0110000001",img:"https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=85"},
{id:4,make:"Ford",model:"Ranger 2.0 Bi-Turbo",year:2024,price:549900,km:18000,gear:"Automatic",fuel:"Diesel",location:"Cape Town",type:"Bakkie",featured:true,dealer:"Cape Coast Auto",phone:"0210000000",img:"https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=1200&q=85"},
{id:5,make:"Hyundai",model:"Tucson 2.0 Executive",year:2022,price:319900,km:39000,gear:"Automatic",fuel:"Petrol",location:"Durban",type:"SUV",featured:false,dealer:"Coastal Motors",phone:"0310000000",img:"https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1200&q=85"},
{id:6,make:"Mercedes-Benz",model:"C200 AMG Line",year:2023,price:679900,km:24000,gear:"Automatic",fuel:"Petrol",location:"Johannesburg",type:"Sedan",featured:true,dealer:"Executive Auto",phone:"0110000002",img:"https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=85"}];
const DEALERS=[["CARZA Founding Motors","Johannesburg",86,"4.9","C"],["Capital Auto Gallery","Pretoria",54,"4.8","C"],["Premium Drive","Johannesburg",41,"4.9","P"]];
const money=n=>"R"+n.toLocaleString("en-ZA");
function card(c){return `<article class="car"><img src="${c.img}" alt="${c.make} ${c.model}"><div class="carbody"><h3>${c.year} ${c.make} ${c.model}</h3><div class="price">${money(c.price)}</div><div class="meta">${c.km.toLocaleString()} km · ${c.gear} · ${c.fuel} · ${c.location}</div><button class="view" onclick="openCar(${c.id})">VIEW CAR</button></div></article>`}
function render(list=CARS){const g=document.querySelector("#cars");if(!g)return;document.querySelector("#count").textContent=list.length+" vehicles found.";g.innerHTML=list.map(card).join("")}
function filterCars(){let q=(document.querySelector("#q")?.value||"").toLowerCase(),loc=document.querySelector("#loc")?.value||"",max=+(document.querySelector("#max")?.value||Infinity),type=document.querySelector("#type")?.value||"",r=CARS.filter(c=>(!q||(`${c.make} ${c.model} ${c.type}`).toLowerCase().includes(q))&&(!loc||c.location===loc)&&c.price<=max&&(!type||c.type===type));let s=document.querySelector("#sort")?.value;if(s==="low")r.sort((a,b)=>a.price-b.price);if(s==="high")r.sort((a,b)=>b.price-a.price);if(s==="year")r.sort((a,b)=>b.year-a.year);render(r)}
function goSearch(){const p=new URLSearchParams({q:document.querySelector("#q").value,loc:document.querySelector("#loc").value,max:document.querySelector("#max").value});location.href="cars.html?"+p}
function openCar(id){const c=CARS.find(x=>x.id===id);if(!document.querySelector("#modal"))return;document.querySelector("#modalbody").innerHTML=`<img src="${c.img}" alt=""><h2>${c.year} ${c.make} ${c.model}</h2><b>${money(c.price)}</b><p>${c.km.toLocaleString()} km · ${c.gear} · ${c.fuel} · ${c.location}<br>Dealer: ${c.dealer}</p><a href="tel:${c.phone}">Call dealer</a><a target="_blank" href="https://wa.me/27${c.phone.replace(/^0/,"")}">WhatsApp dealer</a>`;document.querySelector("#modal").classList.remove("hidden")}
function closeModal(){document.querySelector("#modal")?.classList.add("hidden")}
function toggleMenu(){const n=document.querySelector("nav");if(n){n.style.display=n.style.display==="flex"?"":"flex";n.style.position="absolute";n.style.top="72px";n.style.left="12px";n.style.right="12px";n.style.background="#fff";n.style.padding="18px";n.style.flexDirection="column";n.style.border="1px solid #eee";n.style.borderRadius="14px"}}
const f=document.querySelector("#featured");if(f)f.innerHTML=CARS.filter(c=>c.featured).slice(0,3).map(card).join("");
const d=document.querySelector("#dealers");if(d)d.innerHTML=DEALERS.map(x=>`<article class="dealer"><div class="dealericon">${x[4]}</div><h3>${x[0]}</h3><p>📍 ${x[1]}</p><hr><b>${x[2]} vehicles</b> · ★ ${x[3]}</article>`).join("");
const s=document.querySelector("#stock");if(s)s.innerHTML=CARS.slice(0,4).map(c=>`<div class="stockrow"><img src="${c.img}"><div><strong>${c.year} ${c.make} ${c.model}</strong><small>${money(c.price)} · ${c.km.toLocaleString()} km</small></div></div>`).join("");
if(document.querySelector("#cars")){const p=new URLSearchParams(location.search);if(p.has("type"))document.querySelector("#type").value=p.get("type");render();if(p.has("type"))filterCars()}
